/*!
 * =====================================
 * Theme Name : rm-kyc-module
 * Version :  v1.0.0
 * Copyright : Arun Kumar Gupta
 * @license : ISC
 * About : globecapital.com PMS web App design
 * =====================================
 */
function svgInline(){jQuery("img.svg").each((function(){var e=jQuery(this),t=e.attr("id"),o=e.attr("class"),i=e.attr("src");jQuery.get(i,(function(i){var a=jQuery(i).find("svg");void 0!==t&&(a=a.attr("id",t)),void 0!==o&&(a=a.attr("class",o+" replaced-svg")),a=a.removeAttr("xmlns:a"),e.replaceWith(a)}),"xml")}))}function aosAnimate(){AOS.init({offset:0,duration:800,easing:"ease-in-out-cubic",once:!0})}$((function(){$.icodetutsfrminput.init(),$("body").prepend("<div id='move-top' class='btn btn-theme hoverable move-top'><i class='fa fa-arrow-up'></i></div>");var e="html,body";navigator.userAgent.match(/opera/i)&&(e="html"),$("#move-top").hide(),jQuery(window).on("scroll",(function(){$(this).scrollTop()>180?$("#move-top").fadeIn():$("#move-top").fadeOut()})),jQuery("#move-top").on("click",(function(t){jQuery(e).animate({scrollTop:0},{duration:600}),t.preventDefault()}));$(".modalLoop").on("show.bs.modal",(function(e){var t=$(this),o=$(".modalLoop:visible").not($(this));if(o.length)return o.modal("hide"),o.one("hidden.bs.modal",(function(e){t.modal("show")})),!1})),$(".modalLoop").on("shown.bs.modal",(function(){$(this).find("[autofocus]").focus(),$.icodetutsfrminput.init()})),$.fn.fileUploader=function(e){this.closest(".files").on("change",(function(t){for(var o=0;o<t.target.files.length;o++)e.push(t.target.files[o]);var i,a=[];for(o=0;i=t.target.files[o];o++){var n='<a class="removeFile" href="#" data-fileid="'+o+'"></a>';a.push("<li><span>",escape(i.name),"-",i.size," bytes.</span> ",n,"</li> ")}$(this).children(".fileList").append(a.join(""))}))},$(".pickDate").datepicker({showOtherMonths:!0,selectOtherMonths:!0,dateFormat:"dd-mm-yy",showAnim:"fadeIn",changeMonth:!0,changeYear:!0,autoclose:!0,prevText:'<i class="fa fa-chevron-left"></i>',nextText:'<i class="fa fa-chevron-right"></i>',afterShow:function(){$(".ui-datepicker-prev").remove().append('<i class="fa fa-chevron-left icons"></i>'),$(".ui-datepicker-next").remove().append('<i class="fa fa-chevron-right icons"></i>')}}),$(".pickDate").attr("autocomplete","off")})),$((function(){$(".dob").length&&$(".dob").datepicker({dateFormat:"dd M yy",changeMonth:!0,changeYear:!0,yearRange:"-90:+00"})})),$(window).on("load resize",(function(){var e=$(window).height(),t=$(".siteNavbar").outerHeight(),o=$(".page-footer").outerHeight();$(".pages").css({minHeight:e-(t+o)})})),$(window).on("load",(function(){aosAnimate(),svgInline(),$(window).width()<768&&$("div").each((function(){$(this).attr("data-aos-delay","0")}))}));
//# sourceMappingURL=js-maps/app-bundal.js.map
