/*!
 * =====================================
 * Theme Name : rm-kyc-module
 * Version :  v1.0.0
 * Copyright : Arun Kumar Gupta
 * @license : ISC
 * About : globecapital.com PMS web App design
 * =====================================
 */
$((function(){$.icodetutsfrminput.init();$("body").prepend("<div id='move-top' class='btn btn-theme hoverable move-top'><i class='fa fa-arrow-up'></i></div>");var e="html,body";if(navigator.userAgent.match(/opera/i)){e="html"}$("#move-top").hide();jQuery(window).on("scroll",(function(){if($(this).scrollTop()>180){$("#move-top").fadeIn()}else{$("#move-top").fadeOut()}}));jQuery("#move-top").on("click",(function(t){jQuery(e).animate({scrollTop:0},{duration:600});t.preventDefault()}));var t=".modalLoop";$(".modalLoop").on("show.bs.modal",(function(e){var i=$(this);var a=$(t+":visible").not($(this));if(a.length){a.modal("hide");a.one("hidden.bs.modal",(function(e){i.modal("show")}));return false}}));$(".modalLoop").on("shown.bs.modal",(function(){$(this).find("[autofocus]").focus()}));$.fn.fileUploader=function(e){this.closest(".files").on("change",(function(t){for(var i=0;i<t.target.files.length;i++){e.push(t.target.files[i])}var a=[];for(var i=0,o;o=t.target.files[i];i++){var n='<a class="removeFile" href="#" data-fileid="'+i+'"></a>';a.push("<li><span>",escape(o.name),"-",o.size," bytes.</span> ",n,"</li> ")}$(this).children(".fileList").append(a.join(""))}))};$(".pickDate").datepicker({showOtherMonths:true,selectOtherMonths:true,dateFormat:"dd-mm-yy",showAnim:"fadeIn",changeMonth:true,changeYear:true,autoclose:true,prevText:'<i class="fa fa-chevron-left"></i>',nextText:'<i class="fa fa-chevron-right"></i>',afterShow:function(){$(".ui-datepicker-prev").remove().append('<i class="fa fa-chevron-left icons"></i>');$(".ui-datepicker-next").remove().append('<i class="fa fa-chevron-right icons"></i>')}});$(".pickDate").attr("autocomplete","off")}));$(window).on("load resize",(function(){var e=$(window).height();var t=$(".siteNavbar").outerHeight();var i=$(".page-footer").outerHeight();void 0;$(".pages").css({minHeight:e-(t+i)})}));function svgInline(){jQuery("img.svg").each((function(){var e=jQuery(this);var t=e.attr("id");var i=e.attr("class");var a=e.attr("src");jQuery.get(a,(function(a){var o=jQuery(a).find("svg");if(typeof t!=="undefined"){o=o.attr("id",t)}if(typeof i!=="undefined"){o=o.attr("class",i+" replaced-svg")}o=o.removeAttr("xmlns:a");e.replaceWith(o)}),"xml")}))}function aosAnimate(){AOS.init({offset:0,duration:800,easing:"ease-in-out-cubic",once:true})}$(window).on("load",(function(){aosAnimate();svgInline();$(".ich_checkbox input").each((function(){$(this).prop("checked")?$(this).parents(".ich_checkbox").addClass("checked"):$(this).parents(".ich_checkbox").removeClass("checked")}));$(".ich_radio input").each((function(){$(this).prop("checked")?$(this).parents(".ich_radio").addClass("checked"):$(this).parents(".ich_radio").removeClass("checked")}));if($(window).width()<768){$("div").each((function(){$(this).attr("data-aos-delay","0")}))}}));
//# sourceMappingURL=js-maps/app-bundal.js.map
